apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nzbget
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
spec:
  rules:
  - host: nzbget.$DOMAIN
    http:
      paths:
        - backend:
            serviceName: nzbget
            servicePort: 6789
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
spec:
  ports:
  - name: nzbget
    port: 6789
  type: ExternalName
  externalName: swarm