apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-node-red
  namespace: default
spec:
  selector:
    matchLabels:
      app: node-red
  fileGroups:
  - path: /data
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g
    storageSecretName: restic-secret
  schedule: '@daily'
  volumeMounts:
  - mountPath: /data
    name: data
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true