service:
  type: NodePort
persistence:
  enabled: true
  storageClass: "nfs-storage-on-k8s-host"
resources:
  limits:
    memory: 4Gi
    cpu: 4
config:
  opentsdb:
    enabled: true
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag