apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph
---
apiVersion: ceph.rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    location:
    config:
      metadataDevice:
      storeType: bluestore
      databaseSizeMB: "1024" # this value can be removed for environments with normal sized disks (100 GB or larger)
      journalSizeMB: "1024"  # this value can be removed for environments with normal sized disks (20 GB or larger)
    nodes:
    - name: "k8s"
      directories:         # specific directories to use for storage can be specified for each node
      - path: "/mnt/rook"
    - name: "k8s-b"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdb"
    - name: "k8s-c"
      devices:             # specific devices to use for storage can be specified for each node
      - name: "sdb"
