apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
spec:
  rules:
  - host: grafana.$DOMAIN
    http:
      paths:
        - backend:
            serviceName: grafana
            servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - name: grafana
    port: 3000
  type: ExternalName
  externalName: swarm