apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
spec:
  rules:
  - host: plex.$DOMAIN
    http:
      paths:
        - backend:
            serviceName: plex
            servicePort: 32400
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
  - name: plex
    port: 32400
  type: ExternalName
  externalName: $DOMAIN