image: containous/traefik # TODO: replace with 'traefik' when PR 3231 is baked into a release
imageTag: c37b040217435c1f1683fa7466b6d4ac3002d878 # TODO: replace with latest or some other appropriate tag when PR 3231 is baked into a release
serviceType : NodePort
externalTrafficPolicy: Local
replicas: 3
debug:
  enabled: true
ssl:
  enabled: true
  enforced: true
  insecureSkipVerify : true
acme:
  enabled: true
  email: $EMAIL
  staging: false
  logging: true
  challengeType: http-01
  persistence:
    enabled: true
    storageClass: "rook-ceph-block"
consul:
  enabled: true
  endpoint: consul-consul:8500
dashboard:
  enabled: true
  domain: t.k.$DOMAIN
  auth :
    basic:
       $TRAEFIK_AUTH
  statistics:
    recentErrors: 25
service:
  nodePorts:
    http: "32033"
    https: "32121"
rbac:
  enabled: true
deployment:
  hostPort:
    httpEnabled: true
    httpsEnabled: true
    dashboardEnabled: true
