image: containous/traefik # TODO: replace with 'traefik' when PR 3231 is baked into a release
# imageTag: experimental # TODO: replace with latest or some other appropriate tag when PR 3231 is baked into a release
imageTag: experimental
serviceType : NodePort
externalTrafficPolicy: Cluster
replicas: 1
memoryLimit: 100Mi
cpuLimit: 1
debug:
  enabled: true
ssl:
  enabled: true
  enforced: true
  insecureSkipVerify : true
acme:
  enabled: true
  email: $EMAIL
  staging: false
  logging: true
  domains:
    enabled: true
    domainsList:
      - main: "*.$DOMAIN"
      - sans:
        - "$DOMAIN"
  challengeType: dns-01
  dnsProvider:
    name: digitalocean
    digitalocean:
      DO_AUTH_TOKEN: "$DO_AUTH_TOKEN"
  persistence:
    enabled: true
    storageClass: "nfs-storage-on-k8s-host"
dashboard:
  enabled: true
  domain: t.k.$DOMAIN
  auth :
    basic:
       $TRAEFIK_AUTH
  statistics:
    recentErrors: 25
service:
  nodePorts:
    http: "32033"
    https: "32121"
rbac:
  enabled: true
deployment:
  hostPort:
    httpEnabled: true
    httpsEnabled: true
    dashboardEnabled: true
