imageTag: 1.7.6
serviceType : LoadBalancer
externalTrafficPolicy: Local
loadBalancerIP: 10.0.7.91
replicas: 2
memoryLimit: 100Mi
cpuLimit: 1
startupArguments:
  - --ping
  - --acme.dnschallenge.resolvers="8.8.8.8"
debug:
  enabled: false
rbac:
  enabled: true
ssl:
  enabled: true
  enforced: true
  insecureSkipVerify : true
kvprovider:
  storeAcme: true
  consul:
    endpoint: consul:8500
    watch: true
    prefix: traefik
acme:
  enabled: true
  email: $EMAIL
  staging: false
  logging: true
  domains:
    enabled: true
    domainsList:
      - main: "*.$DOMAIN"
      - sans:
        - "$DOMAIN"
      - main: "*.k.$DOMAIN"
      - main: "*.nd.$DOMAIN"
      - main: "*.ha.$DOMAIN"
  challengeType: dns-01
  dnsProvider:
    name: cloudflare
    cloudflare:
      CLOUDFLARE_EMAIL: $EMAIL
      CLOUDFLARE_API_KEY: "$CF_API_KEY"
  delayBeforeCheck: 120
  persistence:
    enabled: false
dashboard:
  enabled: true
  domain: t.k.$DOMAIN
  auth :
    basic:
       $TRAEFIK_AUTH
  statistics:
    recentErrors: 25
deployment:
  hostPort:
    dashboardEnabled: true
keel:
  policy: "minor"
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image
      tag: imageTag
