db:
  user: homeassistant
  name: homeassistant
replication:
  enabled: false
master:
  persistence:
    enabled: true
    storageClass: "nfs-storage-on-k8s-host"
    size: 5Gi
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
