mysqlUser: "homeassistant"
mysqlDatabase: "homeassistant"
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
  annotations: {}
metrics:
  enabled: true
keel:
  policy: minor
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image
      tag: imageTag
