image:
  tag: 0.82.1
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: nfs-client
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
extraEnv:
  CAMERA_AUTH: ''
configurator:
  enabled: true
  image:
    tag: 0.3.3-x86_64
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
    - repository: configurator.image.repository
      tag: configurator.image.tag
