image:
  tag: 14
mariadb:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 8Gi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
nextcloudUsername: admin
serviceType: ClusterIP
persistence:
  apache:
    enabled: false
  nextcloud:
    enabled: true
    existingClaim: "nfs-data-nextcloud-pvc-10g"
  extraExistingClaimMounts:
    - name: external-mount
      mountPath: /external/Audiobooks
      existingClaim: nfs-media-audiobooks-pvc-10g
      readOnly: true
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag