image:
  tag: "6.4.3"
master:
  persistence:
    enabled: true
    storageClass: "longhorn"
keel:
  policy: minor
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
