backend:
  type: es
  es:
    host: elasticsearch
    port: 9200
keel:
  policy: minor
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.fluent_bit.repository
      tag: image.fluent_bit.tag