debug: true
config:
    delay: 3600
    influxdb:
        host: influxdb-influxdb
        port: 8086
        database: comcast
keel:
  policy: force
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag