persistence:
  enabled: true
  storageClass: "nfs-storage-on-k8s-host"
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag