apiVersion: v1
kind: Secret
metadata:
  namespace: heptio-ark
  name: cloud-credentials
  labels:
    component: minio
stringData:
  cloud: |
    [default]
    aws_access_key_id = $MINIO_ACCESS_KEY
    aws_secret_access_key = $MINIO_SECRET_KEY