apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: node-red
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "traefik-basic-auth-jeff"
spec:
  rules:
  - host: node-red.$DOMAIN
    http:
      paths:
        - backend:
            serviceName: node-red
            servicePort: 1880
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  ports:
  - name: node-red
    port: 1880
  type: ExternalName
  externalName: swarm