apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
spec:
  rules:
  - host: radarr.$DOMAIN
    http:
      paths:
        - backend:
            serviceName: radarr
            servicePort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
  - name: radarr
    port: 7878
  type: ExternalName
  externalName: swarm