image:
  tag: 1.14.1.5488-cc260c476
kubePlex:
  enabled: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
timezone: "America/New_York"
service:
  type: LoadBalancer
  loadBalancerIP: 10.0.7.89
persistence:
  transcode:
    enabled: true
    claimName: nfs-data-pvc-10g
    subPath: plex
  data:
    enabled: true
    claimName: nfs-media-pvc-10g
keel:
  policy: "regexp:^([0-9]+.[0-9]+.[0-9]+.[0-9]+-.+)$"
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
