service:
  type: LoadBalancer
  loadBalancerIP: 10.0.7.88
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
timezone: "America/New_York"
persistence:
  downloads:
    enabled: true
    existingClaim: nfs-media-pvc-10g
    subPath: Downloads
keel:
  policy: "regexp:^([0-9][0-9][0-9]+)$"
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
