apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minio
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
spec:
  rules:
  - host: minio.$DOMAIN
    http:
      paths:
        - backend:
            serviceName: minio
            servicePort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
  - name: minio
    port: 9002
  type: ExternalName
  externalName: swarm