apiVersion: stash.appscode.com/v1alpha1
kind: Restic
metadata:
  name: stash-grafana
  namespace: default
spec:
  selector:
    matchLabels:
      app: grafana
  fileGroups:
  - path: /var/lib/grafana
    retentionPolicyName: 'keep-last-5'
  backend:
    local:
      mountPath: /mnt/backup/
      persistentVolumeClaim:
          claimName: nfs-backup-restic-pv-10g
    storageSecretName: restic-secret
  schedule: '@daily'
  volumeMounts:
  - mountPath: /var/lib/grafana
    name: storage
  retentionPolicies:
  - name: 'keep-last-5'
    keepLast: 5
    prune: true