persistence:
  enabled: true
  storageClassName: "nfs-storage-on-k8s-host"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
