apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxmox-b-nd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: proxmox-b.nd.$DOMAIN
    http:
      paths:
      - backend:
          serviceName: proxmox-b-nd
          servicePort: 19999
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-b-nd
spec:
  ports:
  - name: http
    port: 19999
  type: ExternalName
  externalName: proxmox-b