apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chronograf
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "false"
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "traefik-basic-auth-jeff"
spec:
  rules:
  - host: chronograf.$DOMAIN
    http:
      paths:
        - backend:
            serviceName: chronograf
            servicePort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
spec:
  ports:
  - name: chronograf
    port: 8087
  type: ExternalName
  externalName: swarm