persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
TZ: "America/New York"
runAsRoot: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
