image:
  tag: 5.9
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 20Gi
  storageClass: rook-ceph-block
TZ: "America/New York"
runAsRoot: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
controllerService:
  nodePort: 32287
stunService:
  nodePort: 30443
keel:
  policy: all
  trigger: poll
  pollSchedule: "@every 1h"
  images:
    - repository: image.repository
      tag: image.tag
